 /**
 *  \file    KsCmakeDef.hpp
 *  \brief   This File is generated by CMAKE
 */

/* ! -- Do Not Hand Edit - This File is generated by CMAKE -- ! */

#ifndef _KS_CONFIG_H
#define _KS_CONFIG_H

/** KernelShark Version number. */
#define KS_VERSION_STRING "1.0.0"

/** KernelShark installation prefix path. */
#define _INSTALL_PREFIX "/usr/local"

/** KernelShark plugins installation prefix path. */
#define KS_PLUGIN_INSTALL_PREFIX "/usr/local/lib/kernelshark/plugins/"

/** Location of the trace-cmd executable. */
#define TRACECMD_EXECUTABLE "/usr/local/bin/trace-cmd"

/** "pkexec" executable. */
#define DO_AS_ROOT "/usr/bin/pkexec"

#ifdef __cplusplus

	#include <QString>

	/**
	 * String containing semicolon-separated list of plugin names.
	 * The plugins to be loaded when KernelShark starts are tagged
	 * with "default".
	 */
	const QString plugins = "sched_events default;missed_events default";

#endif /* __cplusplus */

#endif // _KS_CONFIG_H
